# Generated by Django 5.2 on 2025-04-05 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='users',
        ),
    ]
